.TH lybniz 1 "October 20, 2006"
.SH NAME
lybniz - mathematical function graph plotter
.SH DESCRIPTION
.PP
Lybniz is a simple desktop graph plotter. It can currently plot three
functions and allows you to navigate the plot. Functions are entered
in Python notation, eg sin(x)/x ; 2*x**2 + 3*x - 4.
.PP
.SH HOMEPAGE
http://lybniz2.sourceforge.net/
.SH AUTHOR
This manual page was written by Varun Hiremath <varunhiremath@gmail.com>,
for the Debian project (but may be used by others).
